exclude:
- /truffle/truffle.js
- /truffle/build/.*
- /truffle/utils/.*
- /truffle/etherscan/.*
- /www/node_modules/.*
- /www/app/js/app.js
- /www/app/js/sigmajs/.*
- /www/app/lib/.*
- /www/app/js/blockies/.*
component_depth: 2
languages:
- solidity
- javascript